### ISSUE TITLE
Request for the scripts on inference steps?

### ISSUE THREAD

**Issue by zhanhl316** [rooshenas/ebr_mt#1]
Hi all,

    Thank you for sharing your codes! That's a fantastic and very interesting work! I like it quite much!
     A small question:
         I just find the training scripts in this repo. May I know how to utilize the well-trained EBR model on the inference steps?
    Thank you very much!

Best,

**Comment by rooshenas** [comment]
Please see ebr_mt/src/fairseq/inference/
